<a href="https://colab.research.google.com/github/YagyanshB/pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. Pytorch Fundamentals

In [3]:
# importing the required libraries

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [4]:
# cu124 means cuda version 12.4

### Introduction to Tensors:

Tensors are a way to represent multi-dimensional data.

### Creating a Tensor:

In [110]:
# scalar tensor

scalar = torch.tensor(7)

In [111]:
scalar

tensor(7)

In [112]:
type(scalar)

torch.Tensor

In [113]:
# gives us back the number of dimensions within a tensor

scalar.ndim

0

In [114]:
# get tensor back as python int

scalar.item()

7

In [115]:
# vector

vector = torch.tensor([7,7])

In [116]:
vector

tensor([7, 7])

In [117]:
vector.ndim

1

In [118]:
vector.shape

torch.Size([2])

In [119]:
multivector = torch.tensor([[1,2,3],[4,5,6]])
multivector

tensor([[1, 2, 3],
        [4, 5, 6]])

In [120]:
multivector.ndim

2

In [121]:
# MATRIX

MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [122]:
MATRIX.ndim

2

In [123]:
MATRIX.shape

torch.Size([2, 2])

In [124]:
MATRIX[0]

tensor([7, 8])

In [125]:
MATRIX[1]

tensor([ 9, 10])

In [126]:
MATRIX.item

<function Tensor.item>

In [40]:
# TENSOR

TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                        [7,8,9]]])

In [41]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [44]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [45]:
TENSOR.ndim

3

In [46]:
TENSOR.shape

torch.Size([1, 3, 3])

In [49]:
MYTENSOR = torch.tensor([[[[[[[8921], [1292], [2809]]]]]]])

In [50]:
MYTENSOR.ndim

7

In [51]:
MYTENSOR.shape

torch.Size([1, 1, 1, 1, 1, 3, 1])

### Random tensors:

Why random tensors?

They are important because the way many neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better represent the data.

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [127]:
# creating a random tensor using pytorch of size and shape

random_tensor = torch.rand(28,28)
random_tensor

tensor([[0.2065, 0.1704, 0.5177, 0.8942, 0.2646, 0.5921, 0.4966, 0.1927, 0.2799,
         0.4678, 0.6927, 0.7677, 0.6283, 0.3108, 0.2604, 0.7708, 0.1082, 0.6592,
         0.0571, 0.6115, 0.4251, 0.9363, 0.4117, 0.3773, 0.6997, 0.6902, 0.8536,
         0.9963],
        [0.4573, 0.6158, 0.2695, 0.7463, 0.3580, 0.4440, 0.8429, 0.6599, 0.7584,
         0.1103, 0.8954, 0.0525, 0.1553, 0.0345, 0.8347, 0.6085, 0.6914, 0.7135,
         0.1723, 0.3291, 0.2779, 0.6716, 0.5296, 0.9560, 0.1754, 0.7978, 0.3234,
         0.5511],
        [0.1526, 0.9938, 0.0350, 0.4501, 0.4627, 0.5348, 0.0108, 0.9868, 0.7446,
         0.4836, 0.6583, 0.9741, 0.1107, 0.6661, 0.5555, 0.2705, 0.9543, 0.4806,
         0.9346, 0.4731, 0.3161, 0.4751, 0.5339, 0.5758, 0.1000, 0.2717, 0.6547,
         0.3484],
        [0.9255, 0.5139, 0.8471, 0.6741, 0.6887, 0.5048, 0.2506, 0.1470, 0.0306,
         0.5333, 0.9650, 0.9196, 0.6759, 0.9717, 0.3206, 0.2550, 0.0441, 0.5846,
         0.2251, 0.6127, 0.9899, 0.9581, 0.9193, 0.7029

In [128]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([28, 28]))

In [129]:
another_random_tensor = torch.rand(10,10,10)
another_random_tensor

tensor([[[7.1035e-01, 7.3306e-01, 8.4377e-01, 5.0863e-02, 8.6580e-01,
          2.1090e-01, 8.2110e-01, 1.7834e-01, 8.9430e-01, 4.7174e-01],
         [6.6678e-01, 2.4858e-01, 1.9036e-01, 9.5331e-01, 1.6008e-01,
          3.2226e-01, 5.8220e-01, 5.1786e-01, 7.5879e-02, 9.0023e-01],
         [2.3144e-01, 7.6476e-02, 6.5047e-01, 8.9416e-01, 9.0150e-01,
          9.7926e-01, 4.3463e-01, 7.8031e-01, 6.1640e-01, 7.1243e-01],
         [6.2312e-01, 6.1230e-01, 1.3149e-01, 8.1326e-01, 7.5325e-01,
          9.4340e-01, 5.9876e-01, 5.0581e-01, 6.0617e-01, 2.6762e-01],
         [4.2377e-02, 7.2871e-01, 5.9014e-01, 9.2200e-01, 7.6438e-01,
          3.8622e-01, 1.3646e-01, 1.9114e-01, 5.1826e-01, 1.5736e-02],
         [8.0597e-01, 5.9674e-01, 8.4014e-03, 4.7436e-01, 3.9134e-01,
          7.6981e-01, 7.6157e-01, 2.3572e-01, 5.1091e-01, 3.2375e-01],
         [3.5832e-01, 5.0492e-01, 6.4316e-01, 3.4102e-01, 7.3064e-01,
          6.9949e-01, 8.2999e-01, 9.1253e-01, 6.5315e-01, 3.0003e-01],
         [5.9

In [130]:
another_random_tensor.ndim, another_random_tensor.shape

(3, torch.Size([10, 10, 10]))

### Creating a random tensor with simillar shape to an image tensor:

In [72]:
random_image_size_tensor = torch.rand(size =(224,224,3)) # height, width, color channels being red, blue and green

In [73]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeores and Ones:

In [76]:
# create a tensor of all zeroes

zeros = torch.zeros(size =(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [78]:
1 * zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [79]:
# create a tensor of all ones

ones = torch.ones(size =(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [82]:
ones.dtype

torch.float32

In [86]:
### Creating a range of tensors

torch.arange(0,11)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
one_to_thousand = torch.arange(start = 1, end = 1000, step = 77)
one_to_thousand

tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])

In [91]:
one_to_thousand.shape

torch.Size([13])

In [92]:
one_to_thousand.ndim

1

In [96]:
one_to_thousand[9]

tensor(694)

In [97]:
# creating tensors like

ten_zeroes = torch.zeros_like(input = one_to_thousand)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [98]:
### Tensor datatypes

In [108]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16, # what datatype is the tensor
                               device = "cpu",        # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients

In [109]:
float_32_tensor.dtype

torch.float16